# Generated by Django 4.0.3 on 2022-04-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Supplier name'),
        ),
    ]
