# Generated by Django 4.0.3 on 2022-08-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='return_policy',
            field=models.CharField(choices=[('C', 'Crédits'), ('P', 'Pertes')], default='P', max_length=500, verbose_name=' Return policy'),
        ),
    ]
