# Generated by Django 4.0.3 on 2022-04-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('departments', '0001_initial'),
        ('suppliers', '0002_alter_supplier_name'),
        ('measures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.IntegerField(unique=True)),
                ('supplier_code', models.CharField(blank=True, max_length=20, null=True)),
                ('plu_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('cash_register_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('case_size', models.IntegerField(blank=True, default=1)),
                ('in_store', models.BooleanField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brands.brand')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measures.measure')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
            options={
                'ordering': ['brand', 'description'],
            },
        ),
    ]
