# Generated by Django 4.0.3 on 2022-08-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_store',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
